name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      # Optional: run tests if you have any
      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t my-code-runner:latest .
          # Optionally, save the image for later deployment steps
          docker save my-code-runner:latest -o docker-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: docker-image.tar

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i docker-image.tar

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Stopping any existing container..."
            docker stop code-runner || true
            docker rm code-runner || true
            echo "Running new container..."
            docker run -d --name code-runner -p 5000:5000 -v /var/run/docker.sock:/var/run/docker.sock my-code-runner:latest
